default:
  datasource:
    file: TRUE # TRUE when external csv or excel should be used, FALSE when db should be used
    filepath: "dev/data/input/input.csv"  # path/to/data.csv if using a file
    db: # not really used right now
      host: "localhost"
      port: 5432
      database: "my_database"
  params:
    pathogen: Pertussis
    strata:
      - age_group
      - community
    signal_detection_period: 6
    signal_detection_algorithm: ears
  shapefile_path: ~
  post-processing:
        min_cases_signals: 4
  report:
    title: "My Signal Report"

pertussis:
  params:
    pathogen: Pertussis
    strata:
      - age_group
      - sex
    signal_detection_period: 6
    signal_detection_algorithm: glm harmonic
    pandemic_correction: TRUE
    intervention_date: 2020-03-18
  shapefile_path: ~


salmonella:
  params:
    pathogen: Salmonella
    strata:
      - subtype
      - county
      - sex
    signal_detection_algorithm: farrington
  shapefile_path: ~
